//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkingSystemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingMaster
    {
        public ParkingMaster()
        {
            this.SlotMasters = new HashSet<SlotMaster>();
        }
    
        public int ParkingID { get; set; }
        public string ParkingName { get; set; }
        public string ParkingAddress { get; set; }
        public string ParkingTemplateName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int NumberOfSlots { get; set; }
        public Nullable<decimal> Min_Latitude { get; set; }
        public Nullable<decimal> Max_Latitude { get; set; }
        public Nullable<decimal> Min_Longitude { get; set; }
        public Nullable<decimal> Max_Longitude { get; set; }
    
        public virtual ICollection<SlotMaster> SlotMasters { get; set; }
    }
}
