//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkingSystemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotMaster
    {
        public SlotMaster()
        {
            this.ParkingSlotTransactions = new HashSet<ParkingSlotTransaction>();
        }
    
        public int SlotID { get; set; }
        public int ParkingID { get; set; }
        public string SlotNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsAcquired { get; set; }
        public Nullable<int> SlotStatus { get; set; }
        public Nullable<int> CurrentUserID { get; set; }
    
        public virtual ParkingMaster ParkingMaster { get; set; }
        public virtual ICollection<ParkingSlotTransaction> ParkingSlotTransactions { get; set; }
    }
}
