//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkingSystemAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartParkingEntities : DbContext
    {
        public SmartParkingEntities()
            : base("name=SmartParkingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ParkingMaster> ParkingMasters { get; set; }
        public DbSet<ParkingSlotTransaction> ParkingSlotTransactions { get; set; }
        public DbSet<SlotMaster> SlotMasters { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<WalletTran> WalletTrans { get; set; }
    }
}
