//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkingSystemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.ParkingSlotTransactions = new HashSet<ParkingSlotTransaction>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string MobileNumber { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ActiveVehicleNumber { get; set; }
        public Nullable<int> WalletAmount { get; set; }
    
        public virtual ICollection<ParkingSlotTransaction> ParkingSlotTransactions { get; set; }
    }
}
