//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkingSystemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTran
    {
        public decimal TransID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string CRDR { get; set; }
        public Nullable<System.DateTime> TransDt { get; set; }
    }
}
